
project_id = "bqgipoqlxizdpryguzac"

[auth]
otp_expiry = 180 # 3 minutes in seconds

[functions.validate-password]
verify_jwt = false

[functions.handle-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false
