
# This is your Supabase project's configuration file.
# https://supabase.io/docs/reference/config

project_id = "bqgipoqlxizdpryguzac"

[functions]
[functions.send-system-email]
verify_jwt = true

[functions.verify-email]
verify_jwt = false

[functions.demo-login]
verify_jwt = false

[functions.create-demo-accounts]
verify_jwt = false
