// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqgipoqlxizdpryguzac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZ2lwb3FseGl6ZHByeWd1emFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTI5NzQsImV4cCI6MjA2MDIyODk3NH0.JVzAtS0e-PC-Pg0GHwm0WNGocMcucO-Dl5ZsF3xhTuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);